name: 'Test'
on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  vim-test:
    name: 'Vim ${{ matrix.vim_version }} on ${{ matrix.platform }}'
    strategy:
      matrix:
        include:
          - vim_version: 'head'
            platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'
          - vim_version: 'head'
            platform: 'MacOS'
            os: 'macos-latest'
            download: 'never'
          - vim_version: 'head'
            platform: 'Windows'
            os: 'windows-latest'
            download: 'always'
          - vim_version: 'v9.1.0000'
            platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'
          - vim_version: 'v9.1.0000'
            platform: 'MacOS'
            os: 'macos-latest'
            download: 'never'
          - vim_version: 'v9.1.0000'
            platform: 'Windows'
            os: 'windows-latest'
            download: 'always'
          - vim_version: 'v9.0.0000'
            platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'
          - vim_version: 'v9.0.0000'
            platform: 'MacOS'
            os: 'macos-latest'
            download: 'never'
          - vim_version: 'v9.0.0000'
            platform: 'Windows'
            os: 'windows-latest'
            download: 'always'

      fail-fast: false

    runs-on: '${{ matrix.os }}'
    timeout-minutes: 10

    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Setup Vim'
        id: 'vim'
        uses: 'thinca/action-setup-vim@v1'
        with:
          vim_version: '${{ matrix.vim_version }}'
          download: '${{ matrix.download }}'
      - name: 'Show Vim version'
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: 'Setup themis.vim'
        uses: 'actions/checkout@v4'
        with:
          repository: 'thinca/vim-themis'
          ref: 'v1.7.0'
          path: 'themis'
      - name: 'Run test'
        env:
          THEMIS_VIM: '${{ steps.vim.outputs.executable }}'
        run: |
          ./themis/bin/themis --reporter dot

  neovim-test:
    name: 'Neovim ${{ matrix.nvim_version }} on ${{ matrix.platform }}'
    strategy:
      matrix:
        include:
          - nvim_version: 'head'
            platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'
          - nvim_version: 'head'
            platform: 'MacOS'
            os: 'macos-latest'
            download: 'never'
          - nvim_version: 'head'
            platform: 'Windows'
            os: 'windows-latest'
            download: 'always'
          - nvim_version: 'v0.10.0'
            platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'
          - nvim_version: 'v0.10.0'
            platform: 'MacOS'
            os: 'macos-latest'
            download: 'never'
          - nvim_version: 'v0.10.0'
            platform: 'Windows'
            os: 'windows-latest'
            download: 'always'
          - nvim_version: 'v0.9.0'
            platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'
          - nvim_version: 'v0.9.0'
            platform: 'MacOS'
            os: 'macos-latest'
            download: 'never'
          - nvim_version: 'v0.9.0'
            platform: 'Windows'
            os: 'windows-latest'
            download: 'always'

      fail-fast: false

    runs-on: '${{ matrix.os }}'
    timeout-minutes: 10

    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Setup Neovim'
        id: 'vim'
        uses: 'thinca/action-setup-vim@v1'
        with:
          vim_type: 'neovim'
          vim_version: '${{ matrix.nvim_version }}'
          download: '${{ matrix.download }}'
      - name: 'Show Neovim version'
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: 'Setup themis.vim'
        uses: 'actions/checkout@v4'
        with:
          repository: 'thinca/vim-themis'
          ref: 'v1.7.0'
          path: 'themis'
      - name: 'Run test'
        env:
          THEMIS_VIM: '${{ steps.vim.outputs.executable }}'
        run: |
          ./themis/bin/themis --reporter dot

  deno-test:
    name: 'Deno unit tests'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10

    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Setup Deno'
        uses: 'denoland/setup-deno@v2'
        with:
          deno-version: 'v2.x'
      - name: 'Run Deno tests'
        run: |
          deno test --allow-all --no-check
